from os import environ

LOG_FORMAT = environ.get(
    "LOG_FORMAT", "%(asctime)s (%(process)d) [%(levelname)8s]: %(message)s"
)

# Prefix for all docker images built in this project, e.g. `project-`
IMAGE_PREFIX = "myproj-"

KUBEVAL_SKIP_KINDS = {"CustomResourceDefinition", "SealedSecret"}

LOG_LEVEL = "INFO"

TEMPLATE_HEADER = """# THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY: poetry run invoke update-from-templates
# GENERATED FROM {file}, DO NOT MODIFY THIS FILE BY HAND
#
"""

# File extension for unsealed secrets. Update .gitignore if you change this.
UNSEALED_SECRETS_EXTENSION = ".unsealed-secrets.yaml"

try:
    from devops.settings_local import *
except ImportError:
    pass
